# -*- coding: utf-8 -*-
"""Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QJx1jIR3zkishN5U5sEuKFPKkmwQUYqK
"""

!pip install -q groq gradio openai-whisper gtts openai

import whisper
from openai import OpenAI
from gtts import gTTS
import gradio as gr
import numpy as np
import os
import json
import re
import time
import random
import requests
from google.colab import userdata

import getpass
OPENROUTER_API_KEY = getpass.getpass("Enter your OpenRouter API key: ")
client = OpenAI(
    base_url="https://openrouter.ai/api/v1",
    api_key=OPENROUTER_API_KEY,
)
print("✅ OpenRouter client ready.")

# Cell 3.5: Auto-discover a working free model

def find_working_free_model():
    # 1. Fetch all models from OpenRouter (public endpoint)
    try:
        models_url = "https://openrouter.ai/api/v1/models"
        resp = requests.get(models_url)
        if resp.status_code != 200:
            print("⚠️ Could not fetch model list. Using fallback list.")
            fallback_models = [
                "meta-llama/llama-3.2-3b-instruct:free",
                "cognitivecomputations/dolphin3.0-r1-mistral-24b:free",
                "microsoft/phi-3-mini-128k-instruct:free"
            ]
            return fallback_models[0], fallback_models
        all_models = resp.json()
        # Filter for free models (IDs ending with ':free')
        free_models = [m["id"] for m in all_models["data"] if m["id"].endswith(":free")]
        if not free_models:
            print("⚠️ No free models found in API response. Using fallback.")
            free_models = [
                "meta-llama/llama-3.2-3b-instruct:free",
                "cognitivecomputations/dolphin3.0-r1-mistral-24b:free",
                "microsoft/phi-3-mini-128k-instruct:free"
            ]
    except Exception as e:
        print(f"⚠️ Error fetching models: {e}. Using fallback list.")
        free_models = [
            "meta-llama/llama-3.2-3b-instruct:free",
            "cognitivecomputations/dolphin3.0-r1-mistral-24b:free",
            "microsoft/phi-3-mini-128k-instruct:free"
        ]

    # 2. Test each free model until one works
    for model in free_models:
        try:
            print(f"Testing model: {model} ...")
            test_response = client.chat.completions.create(
                model=model,
                messages=[{"role": "user", "content": "Say 'working'"}],
                max_tokens=10
            )
            print(f"✅ Model {model} works!")
            return model, free_models
        except Exception as e:
            print(f"   {model} failed: {e}")
            continue

    # If none work, raise error
    raise Exception("❌ No free models are currently working with your API key. Please check your key or add a small payment to OpenRouter.")

WORKING_MODEL, FREE_MODELS_LIST = find_working_free_model()
print(f"\n🎯 Using model: {WORKING_MODEL}")
print("📋 All available free models:", FREE_MODELS_LIST)

print("Loading Whisper model (base)...")
model = whisper.load_model("base")
print("✅ Whisper model loaded.")

# Cell 5: Helper functions with non‑empty feedback guarantee

def call_openrouter_with_retry(messages, model=None, max_tokens=2000, temperature=0.7, max_retries=3, base_delay=2):
    if model is None:
        model = WORKING_MODEL
    for attempt in range(max_retries):
        try:
            response = client.chat.completions.create(
                model=model,
                messages=messages,
                temperature=temperature,
                max_tokens=max_tokens
            )
            return response
        except Exception as e:
            if "429" in str(e) and attempt < max_retries - 1:
                delay = base_delay * (2 ** attempt) + random.uniform(0, 1)
                print(f"⚠️ Rate limit hit. Retrying in {delay:.1f}s...")
                time.sleep(delay)
            else:
                raise e
    raise Exception(f"All retries failed for model {model}")

def generate_questions(domain, num_questions):
    prompt = f"""Generate {num_questions} interview questions for the domain: {domain}.
    Also provide a concise model answer for each question.
    Return the result as a JSON array with objects having keys "question" and "answer".
    Example: [{{"question": "What is Python?", "answer": "Python is a high-level programming language..."}}]
    Only output the JSON, no other text."""

    models_to_try = [WORKING_MODEL] + [m for m in FREE_MODELS_LIST if m != WORKING_MODEL]
    last_error = None
    for model in models_to_try:
        try:
            response = call_openrouter_with_retry(
                messages=[{"role": "user", "content": prompt}],
                model=model,
                max_tokens=2000,
                temperature=0.7
            )
            content = response.choices[0].message.content
            # Parse JSON
            try:
                qa_list = json.loads(content)
                questions = [item["question"] for item in qa_list]
                answers = [item["answer"] for item in qa_list]
            except:
                # Fallback extraction
                lines = content.split('\n')
                questions, answers = [], []
                current_q = None
                for line in lines:
                    line = line.strip()
                    if re.match(r'^\d+\.', line):
                        if current_q:
                            questions.append(current_q)
                        current_q = re.sub(r'^\d+\.\s*', '', line)
                    elif line and current_q and not answers:
                        answers.append(line)
                        current_q = None
                if current_q:
                    questions.append(current_q)
                while len(answers) < len(questions):
                    answers.append("(Model answer not available)")
            # Pad if necessary
            if len(questions) < num_questions:
                for i in range(len(questions), num_questions):
                    questions.append(f"Tell me about {domain} concept #{i+1}")
                    answers.append("No answer provided.")
            return questions[:num_questions], answers[:num_questions]
        except Exception as e:
            last_error = e
            continue
    raise Exception(f"All models failed. Last error: {last_error}")

def evaluate_answer(user_answer, expected_answer, domain):
    prompt = f"""Domain: {domain}
User's answer: "{user_answer}"
Expected answer: "{expected_answer}"

Determine if the user's answer is correct (considering interview context – accept if close enough).
Provide a brief feedback: first state if correct or not, then give the ideal answer.
Keep it to 2-3 sentences."""

    models_to_try = [WORKING_MODEL] + [m for m in FREE_MODELS_LIST if m != WORKING_MODEL]
    for model in models_to_try:
        try:
            response = call_openrouter_with_retry(
                messages=[{"role": "user", "content": prompt}],
                model=model,
                max_tokens=300,
                temperature=0.5
            )
            feedback = response.choices[0].message.content
            # Ensure feedback is not empty
            if feedback and feedback.strip():
                return feedback.strip()
            else:
                print(f"⚠️ Empty feedback from model {model}, using fallback.")
                # Fallback
                return f"Your answer was: '{user_answer}'. The ideal answer is: {expected_answer}"
        except Exception as e:
            print(f"⚠️ Model {model} failed: {e}")
            continue
    # Ultimate fallback
    return f"Unable to evaluate answer. Expected answer: {expected_answer}"

def transcribe(audio_path):
    result = model.transcribe(audio_path)
    return result["text"].strip()

def speak(text):
    if not text or not text.strip():
        text = "I'm sorry, I couldn't generate a response."
    tts = gTTS(text=text, lang='en')
    tts.save("response.mp3")
    return "response.mp3"

# Cell 6: Main processing with clearing support

def start_interview(domain, num_questions, state):
    if not domain or num_questions < 1:
        return (
            "Please enter domain and valid number.",
            None,
            "Invalid input",
            state,
            None,  # answer_audio cleared
            "",    # feedback_text cleared
            None   # feedback_audio cleared
        )
    try:
        qs, ans = generate_questions(domain, int(num_questions))
    except Exception as e:
        error_msg = f"❌ Failed to generate questions: {str(e)}"
        return (
            error_msg,
            None,
            error_msg,
            state,
            None,
            "",
            None
        )
    new_state = {
        "domain": domain,
        "questions": qs,
        "answers": ans,
        "current_index": 0,
        "num_questions": len(qs),
        "conversation": []
    }
    first_q = qs[0]
    try:
        audio_q = speak(first_q)
    except Exception as e:
        audio_q = None
    return (
        first_q,
        audio_q,
        f"Question 1 of {len(qs)}",
        new_state,
        None,  # answer_audio cleared
        "",    # feedback_text cleared
        None   # feedback_audio cleared
    )

def submit_answer(audio_path, state):
    if state is None or state["current_index"] >= state["num_questions"]:
        return "No active question.", None, state
    idx = state["current_index"]
    question = state["questions"][idx]
    expected = state["answers"][idx]
    domain = state["domain"]

    try:
        user_answer = transcribe(audio_path)
    except Exception as e:
        return f"Transcription error: {e}", None, state

    try:
        feedback = evaluate_answer(user_answer, expected, domain)
    except Exception as e:
        feedback = f"Evaluation error: {e}"

    if not feedback or not feedback.strip():
        feedback = f"Your answer was: '{user_answer}'. The ideal answer is: {expected}"

    try:
        audio_fb = speak(feedback)
    except Exception as e:
        audio_fb = None

    state["conversation"].append({
        "question": question,
        "user": user_answer,
        "expected": expected,
        "feedback": feedback
    })
    return feedback, audio_fb, state

def next_question(state):
    if state is None:
        return (
            "Start interview first.",
            None,
            "0/0",
            state,
            None,
            "",
            None
        )
    idx = state["current_index"] + 1
    if idx < state["num_questions"]:
        state["current_index"] = idx
        q = state["questions"][idx]
        try:
            audio_q = speak(q)
        except Exception as e:
            audio_q = None
        return (
            q,
            audio_q,
            f"Question {idx+1} of {state['num_questions']}",
            state,
            None,  # answer_audio cleared
            "",    # feedback_text cleared
            None   # feedback_audio cleared
        )
    else:
        return (
            "🎉 Interview complete! Great job.",
            None,
            f"Completed {state['num_questions']} questions.",
            state,
            None,
            "",
            None
        )

# Cell 7: Improved UI with resizable textboxes and auto‑clear

with gr.Blocks(title="Voice Interview Coach", theme=gr.themes.Soft()) as demo:
    gr.Markdown("# 🎤 Voice‑Based Interview Prep")
    gr.Markdown("Choose your domain and number of questions, then start practicing.")

    with gr.Row():
        domain_input = gr.Textbox(
            label="Domain",
            placeholder="e.g., Python, ML, DBMS",
            scale=3
        )
        num_input = gr.Number(
            label="Questions",
            value=3,
            minimum=1,
            maximum=10,
            step=1,
            scale=1
        )
        start_btn = gr.Button("Generate & Start Interview", variant="primary", scale=1)

    state = gr.State(None)

    gr.Markdown("---")
    gr.Markdown("## Current Question")
    with gr.Row():
        question_text = gr.Textbox(
            label="Question",
            interactive=False,
            lines=3,
            max_lines=20,
            scale=3
        )
        question_audio = gr.Audio(type="filepath", label="Listen", autoplay=True, scale=1)

    progress = gr.Textbox(
        label="Progress",
        value="Not started",
        interactive=False,
        lines=1
    )

    gr.Markdown("---")
    gr.Markdown("## Your Answer")
    with gr.Row():
        answer_audio = gr.Audio(type="filepath", label="Speak your answer", scale=3)
        submit_btn = gr.Button("Submit Answer", variant="primary", scale=1)

    gr.Markdown("---")
    gr.Markdown("## Feedback")
    with gr.Row():
        feedback_text = gr.Textbox(
            label="Feedback",
            interactive=False,
            lines=3,
            max_lines=20,
            scale=3
        )
        feedback_audio = gr.Audio(type="filepath", label="Listen", autoplay=True, scale=1)

    gr.Markdown("---")
    next_btn = gr.Button("➡️ Next Question", variant="secondary")

    # --- Event Handlers ---

    # Start interview: set first question, clear answer & feedback
    start_btn.click(
        fn=start_interview,
        inputs=[domain_input, num_input, state],
        outputs=[
            question_text,
            question_audio,
            progress,
            state,
            answer_audio,       # cleared
            feedback_text,      # cleared
            feedback_audio      # cleared
        ]
    )

    # Submit answer: update feedback fields only
    submit_btn.click(
        fn=submit_answer,
        inputs=[answer_audio, state],
        outputs=[
            feedback_text,
            feedback_audio,
            state
        ]
    )

    # Next question: update question fields AND clear answer/feedback
    next_btn.click(
        fn=next_question,
        inputs=[state],
        outputs=[
            question_text,
            question_audio,
            progress,
            state,
            answer_audio,       # cleared
            feedback_text,      # cleared
            feedback_audio      # cleared
        ]
    )

demo.launch(share=True, debug=True)